  @extends('layouts.mail')

  @section('content')

<table class="content">
  <tr>
    <td>
      <h4>Hello {{$first_name}},</h4><br>
      <table>
        <tr>
          <td>
            @if(isset($building))
              <p align="center" >
                An alarm has been received for your building at:
              </p>
              <br>
              <h3 align="center">
                {{$building['address1']}},<br>
                {{$building['city']}}, {{$building['state']}}, {{$building['zip']}}<br>
              </h3>
              <hr>
              <br>
            @endif
            <h3 align="center">{{ preg_replace('/\.\ /', '<br>', $alarm['alarm_description']) }}</h3>
            <br>
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="10%"></td>
                <td width="80%">
                  <table border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td class = "page-nav" style="padding: 12px 18px 12px 18px; font-size: 2vw;" align="center">
                        <a href="{{URL::route('alarms', [$building['id'], $system['id']])}}" target="_blank" style="text-decoration: none; color:white;">
                          View Active Alarms
                        </a>
                      </td>
                    </tr>
                  </table>
                </td>
                <td width="10%"></td>
              </tr>
            </table>

            <br>
            <hr>
            <br>
            <h4 align="center">This alarm was generated by the <i>{{$device['name']}}</i> device in the <i>{{$zone}}</i> zone.</h4>
            <br>
            <p align="center" >
              @if(isset($building))
                <span style="font-size:80%;">
                  Building Name -> <b>{{$building['name']}}</b><br>
                  System -> <b>{{$system['name']}}</b><br>
                  <br>
                  You're receiving this message because you are subscribed to <i>{{$alarm_code['description']}}</i> alerts
                  @if(isset($alert['function']))
                    for {{'<i>' .$alert['function'].'</i>'}}
                  @endif
                  .<br>
                </span>
              @else
                You're receiving this message because you are subscribed to administrative alarm
                notifications.
              @endif
            </p>
          </td>
        </tr>
      <tr class="spacer">
      <td></td>
      <td></td>
      <td></td>
      </tr>
      </table>
    </td>
  </tr>
</table>

  @stop
